import type { FastifyInstance } from "fastify";

import { exchangeRoute } from "./exchange.js";
import { approvalRoute } from "./approval.js";
import { agentRoute } from "./agent.js";
import { balanceRoute } from "./balance.js";
import { oauthRoute } from "./oauth.js";
import { openOrdersRoute } from "./openOrders.js";
import { orderStatusRoute } from "./orderStatus.js";
import { preflightRoute } from "./preflight.js";
import { marketsRoute } from "./markets.js";
import { marketStatsRoute } from "./marketStats.js";
import { markPriceRoute } from "./markPrice.js";
import { dexesRoute } from "./dexes.js";
import { l2BookRoute } from "./l2Book.js";
import { userFillsRoute } from "./userFills.js";
import { metricsRoute } from "./metrics.js";
import { outcomesRoute } from "./outcomes.js";
import { predictionRoute } from "./prediction.js";
import { predictionBalanceRoute } from "./predictionBalance.js";
import { predictionExchangeRoute } from "./predictionExchange.js";
import { predictionPaperRoute } from "./predictionPaper.js";
import { predictionUsdcTransferRoute } from "./predictionUsdcTransfer.js";
import { positionsRoute } from "./positions.js";
import { agentTradeRoute } from "./agentTrade.js";
import { agentTradeCandlesRoute } from "./agentTradeCandles.js";
import { agentTradeDepositRoute } from "./agentTradeDeposit.js";

export async function registerRoutes(app: FastifyInstance): Promise<void> {
  await app.register(exchangeRoute);
  await app.register(approvalRoute);
  await app.register(agentRoute);
  await app.register(balanceRoute);
  await app.register(oauthRoute);
  await app.register(openOrdersRoute);
  await app.register(orderStatusRoute);
  await app.register(preflightRoute);
  await app.register(marketsRoute);
  await app.register(marketStatsRoute);
  await app.register(markPriceRoute);
  await app.register(dexesRoute);
  await app.register(l2BookRoute);
  await app.register(userFillsRoute);
  await app.register(metricsRoute);
  await app.register(positionsRoute);
  await app.register(outcomesRoute);
  await app.register(predictionRoute);
  await app.register(predictionBalanceRoute);
  await app.register(predictionExchangeRoute);
  await app.register(predictionPaperRoute);
  await app.register(predictionUsdcTransferRoute);
  await app.register(agentTradeRoute);
  await app.register(agentTradeCandlesRoute);
  await app.register(agentTradeDepositRoute);
}
