import type { AgentInput } from "./agent-provider";

export const AGENT_ANALYSIS_JSON_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [
    "responseType",
    "summary",
    "thesis",
    "side",
    "confidence",
    "receipts",
    "riskNote",
    "whyWrong",
    "warnings",
    "provider",
  ],
  properties: {
    responseType: {
      type: "string",
      enum: ["greeting", "market_read", "trade_proposal", "no_trade", "refusal"],
    },
    summary: { type: "string" },
    thesis: { type: "string" },
    side: { type: "string", enum: ["long", "short", "none"] },
    confidence: { type: "number", minimum: 0, maximum: 1 },
    receipts: {
      type: "array",
      items: {
        type: "object",
        required: ["label", "value", "timestamp"],
        properties: {
          label: { type: "string" },
          value: { type: "string" },
          timestamp: { type: "number" },
        },
      },
    },
    riskNote: { type: "string" },
    whyWrong: { type: "string" },
    orderDraft: {
      type: "object",
      required: ["symbol", "side", "orderType", "sizeBtc", "leverage", "marginMode", "reduceOnly", "fromAgent"],
      properties: {
        symbol: { type: "string" },
        side: { type: "string", enum: ["long", "short"] },
        orderType: { type: "string", enum: ["market", "limit"] },
        sizeBtc: { type: "number", exclusiveMinimum: 0 },
        leverage: { type: "number", exclusiveMinimum: 0 },
        marginMode: { type: "string", enum: ["isolated", "cross"] },
        reduceOnly: { type: "boolean" },
        limitPrice: { type: "number" },
        takeProfit: { type: "number" },
        stopLoss: { type: "number" },
        fromAgent: { type: "boolean", const: true },
        scenarioId: { type: "string" },
      },
    },
    predictionDraft: {
      type: "object",
      required: [
        "kind",
        "questionId",
        "questionName",
        "outcome",
        "outcomeName",
        "side",
        "sideName",
        "action",
        "contracts",
        "limitProbability",
        "tif",
        "paperOnly",
        "fromAgent",
      ],
      properties: {
        kind: { type: "string", const: "prediction_order" },
        questionId: { type: "number" },
        questionName: { type: "string" },
        outcome: { type: "number" },
        outcomeName: { type: "string" },
        side: { type: "number", enum: [0, 1] },
        sideName: { type: "string" },
        action: { type: "string", const: "buy" },
        contracts: { type: "number", exclusiveMinimum: 0 },
        limitProbability: { type: "number", exclusiveMinimum: 0, maximum: 1 },
        tif: { type: "string", enum: ["Ioc", "Gtc"] },
        paperOnly: { type: "boolean" },
        fromAgent: { type: "boolean", const: true },
      },
    },
    warnings: { type: "array", items: { type: "string" } },
    provider: {
      type: "object",
      required: ["name", "deterministic", "generatedAt"],
      properties: {
        name: { type: "string" },
        model: { type: "string" },
        deterministic: { type: "boolean" },
        generatedAt: { type: "number" },
        latencyMs: { type: "number" },
        fallbackReason: { type: "string" },
      },
    },
  },
} as const;

export function buildAgentPrompt(input: AgentInput): string {
  const topBook = {
    bestBid: input.orderBook.bids[0],
    bestAsk: input.orderBook.asks[0],
    bidDepth: input.orderBook.bids.slice(0, 5),
    askDepth: input.orderBook.asks.slice(0, 5),
  };
  const marketSnapshot = {
    symbol: input.market.symbol,
    base: input.market.base,
    markPrice: input.market.markPrice,
    oraclePrice: input.market.oraclePrice,
    fundingRatePct: input.market.fundingRatePct,
    openInterestUsd: input.market.openInterestUsd,
    openInterestChangePct: input.market.openInterestChangePct,
    volume24hUsd: input.market.volume24hUsd,
    liquidityUsd: input.market.liquidityUsd,
    dataAgeSeconds: input.market.dataAgeSeconds,
    source: input.market.source,
  };

  return [
    "You are Agent.trade, a trading analysis assistant. Return JSON only.",
    "Safety rules:",
    "- Never claim execution, fills, placement, cancellation, or wallet signing.",
    "- Draft orders only when the setup is clear and every order still requires user confirmation in Agent.trade.",
    "- For prediction markets, draft predictionDraft only; do not use orderDraft. Prediction drafts are ticket prefills, not submissions.",
    "- Prediction live MVP drafts may only use action=buy. Restricted users may receive paper-only prediction drafts.",
    "- Restricted, unknown, loading, paper, or kill-switch users may draft paper orders only; live orders are unavailable.",
    "- Cite available market data in receipts and say no_trade when data is unclear.",
    "- If price, side, size, or risk cannot be validated, return refusal or no_trade and omit orderDraft.",
    "",
    "Requested prompt:",
    input.requestedPrompt,
    "",
    "Eligibility and allowed state:",
    JSON.stringify(input.eligibility, null, 2),
    "",
    "Market snapshot:",
    JSON.stringify(marketSnapshot, null, 2),
    "",
    "Order book state:",
    JSON.stringify(topBook, null, 2),
    "",
    "Recent trades:",
    JSON.stringify(input.recentTrades.slice(0, 10), null, 2),
    "",
    "Candle summary:",
    JSON.stringify(input.candleSummary, null, 2),
    "",
    "User account summary:",
    JSON.stringify({
      valueKind: input.account.valueKind,
      equityUsd: input.account.equityUsd,
      availableUsd: input.account.availableUsd,
      marginUsedUsd: input.account.marginUsedUsd,
      unrealizedPnlUsd: input.account.unrealizedPnlUsd,
      dailyLiveNotionalUsedUsd: input.account.dailyLiveNotionalUsedUsd,
      selectedPosition: input.selectedPosition,
      exposure: input.exposure,
    }, null, 2),
    "",
    "Freshness:",
    JSON.stringify(input.freshness, null, 2),
    "",
    "Prediction market context:",
    input.prediction ? JSON.stringify(input.prediction, null, 2) : "None",
    "",
    "Output schema:",
    JSON.stringify(AGENT_ANALYSIS_JSON_SCHEMA, null, 2),
  ].join("\n");
}
